name: Python application

on: [push]

env:
  ml-ws-connection: airs-workspace-ent
  ml-ws: airs-workspace-ent
  ml-rg: azure-ml
  ml-ct: cpu-cluster-1
  ml-path: models/diabetes
  ml-exp: exp-test 
  ml-model-name: diabetes-model # Model name
  ml-aks-name: aks-prod # AKS cluster name
  ml-model-path: outputs/ridge_0.90.pkl 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@master
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: install azmlcli
      run: az extension add -n azure-cli-ml
    - name: attach to workspace
      working-directory: ${{env.ml-path}}
      run: az ml folder attach -w ${{env.ml-ws}} -g ${{env.ml-rg}}
